# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow 
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'Statistics in the Community at Johns Hopkins University (STATCOM@JHU)'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: ''

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "STATCOM@JHU connects Biostatistics graduate students with Baltimore nonprofits to provide free data consulting and support."

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on the theme <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

# Main author of the website
# See > authors.yml
author: Emily Potts

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://jhustatcom.github.io'
#baseurl: ''   # leave empty for org site

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/jhustatcom/jhustatcom.github.io/edit/main/

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://jhustatcom.github.io/images/'

# Logo size is 600x80 pixels
logo: "statcom_5.png"

# Gems
gems:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


#       ____              _             __  _
#      / __ \____ _____ _(_)___  ____ _/ /_(_)___  ____
#     / /_/ / __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
#    / ____/ /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
#   /_/    \__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
#               /____/
#
# add back in blog folder to re-enable
paginate: 5                      # Paginates all X entries
paginate_path: "news/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - .gitignore
    - .DS_Store


# The language setting is used in /includes/header.html for html-settings
language: 'en'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      comments: false
      author: STATCOM@JHU    # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      comments: false
      author: STATCOM@JHU    # Default author for posts
      
      

